baseURL = "https://dvontrecoleman.com"
languageCode = "en-us"
title = "Dvontre Coleman"
theme = "prav"

# Set up where page will be published
publishDir = "./docs"

pygmentsCodeFences = "true"
pygmentsStyle = "perldoc"

# If you want to track using GA or use disqus for comments, uncomment the 
# following and add the correct values
#googleanalytics = ""
#disqusShortname = ""

# The settings below are used throughout the theme.
# Please update!
[params]
  title = "Dvontre Coleman"
  tagline = "Software Developer / Hip-Hop Historian"
  author = "Dvontre Coleman"

# If you do not want a social icon, just comment it out
# Please update the example values!
[social]
  email = "mailto:dvontrec@gmail.com"
  twitter = "http://twitter.com/dvontrecoleman"
  github = "https://github.com/dvontrec"
  linkedin = "https://www.linkedin.com/in/dvontrecoleman/"


# Set unsafe mode to allow markdownify to work with goldmark
# This is important. Please do not delete. It is used to re-render markdown
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
