baseURL = "https://dvontrecoleman.com"
languageCode = "en-us"
publishDir = "./docs"
pygmentsCodeFences = "true"
pygmentsStyle = "perldoc"
theme = "prav"
title = "Dvontre Coleman"
[markup.goldmark.renderer]
unsafe = true
[params]
author = "Dvontre Coleman"
tagline = "Software Developer / Hip-Hop Historian"
title = "Dvontre Coleman"
[social]
email = "mailto:dvontrec@gmail.com"
github = "https://github.com/dvontrec"
linkedin = "https://www.linkedin.com/in/dvontrecoleman/"
twitter = "http://twitter.com/dvontrecoleman"
