## Basic Configuration

baseurl = "/" 
builddrafts = true
canonifyurls = false
languageCode = "en-US"

contentdir = "content"
layoutdir = "layouts"
publishdir = "docs"

author = "Dvontre Coleman"
title = "Dvontre Coleman"

theme = "hugo-goa"

## Hugo Built-in Features
disqusShortname = "" # Comment out to disable Disqus.
googleAnalytics = ""
enableRobotsTXT = true

## Site Settings
[params]
author = "Dvontre Coleman"
intro = "Web Developer"
description = "Lets build something"
authorimage = "selfie.jpg"
dateformat = "Jan 2, 2006"

## Site Meta Settings
[params.meta]
description = "Dvontre Coleman's portfolio site"
keywords = "minimalist,blog,goa,hugo,developer,Dvontre,Coleman,Web,Developer,Dvontre Coleman,Shelbyville,Louisville,Kentucky,Western,WKU,University,Code,MEAN,Github,Responsive,aspiring,freelance,hire, "

## Social Accounts
[params.social]
github = "dvontrec"
linkedin = "dvontrecoleman"
twitter = "dvontrecoleman"
email = "dvontrec@gmail.com"

## Extras
[params.extra]
copyright = "© <script type='text/javascript'>var d = new Date();document.write(d.getFullYear());</script> Dvontre Coleman. [Some Rights Reserved](http://creativecommons.org/licenses/by/3.0/)." 
poweredby = true
highlightjs = true

## Main Menu
[[menu.main]]
    name = "about"
    identifier = "about"
    weight = 200
    url = "/about/"
[[menu.main]]
    name = "resume"
    identifier = "resume"
    weight = 200
    url = "/resume/show"
[[menu.main]]
    name = "projects"
    identifier = "projects"
    weight = 300
    url = "/projects/"
